version: '3'

services:

    db:
        image: postgres:9.6
        restart: always
        volumes:
            - dbdata:/var/lib/postgres/
    
    horarioApp:
        depends_on:
            - db
            
volumes:
    dbdata:
